-- Migration: Support 3 decimal places for prices
-- Changes DECIMAL(10,2) columns to DECIMAL(10,3) to support prices like 1.125

ALTER TABLE `products` MODIFY COLUMN `price` DECIMAL(10,3) NOT NULL DEFAULT 0;
ALTER TABLE `products` MODIFY COLUMN `cost_price` DECIMAL(10,3) DEFAULT 0.000;
ALTER TABLE `product_sizes` MODIFY COLUMN `price` DECIMAL(10,3) NOT NULL DEFAULT 0;
ALTER TABLE `orders` MODIFY COLUMN `total` DECIMAL(12,3) NOT NULL DEFAULT 0;
ALTER TABLE `orders` MODIFY COLUMN `tax` DECIMAL(10,3) DEFAULT 0;
ALTER TABLE `orders` MODIFY COLUMN `discount` DECIMAL(10,3) DEFAULT 0;
ALTER TABLE `order_items` MODIFY COLUMN `unit_price` DECIMAL(10,3) NOT NULL DEFAULT 0;
ALTER TABLE `order_items` MODIFY COLUMN `total` DECIMAL(10,3) NOT NULL DEFAULT 0;
ALTER TABLE `payments` MODIFY COLUMN `amount` DECIMAL(10,3) NOT NULL DEFAULT 0;
